package View;

import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import Model.Factura;
import javax.swing.JOptionPane;
import Model.CrearArchivos;

public class Ordenar extends javax.swing.JFrame {
    private DefaultComboBoxModel <Factura> model = new DefaultComboBoxModel <Factura>();
    // We go to the comboBoxModel, in code and parameter we change String for Persona
    private DefaultTableModel tableModel = new DefaultTableModel();
    CrearArchivos archivos = new CrearArchivos();
    String nombre,precio,cantidades,ordenCompra,totalAbsoluto = "0";
    private int cantidad;
    private String cantidadFinal;
    private static String nom;
    
    
    public Ordenar(String nombre) {
        initComponents();
        this.nom = nombre;
        setLocationRelativeTo(null); // This is to put the window in center
        fillModel(); // This is the method we created
        addTableModel(); // This is the method we created for the table
    }
    

    // To put changes, go to window, in the comboboxmodel, in model, we put custom code and we add model or the name of 
    // the reference we use for the object DefaultComboBoxModel
    private void fillModel() {
        
        // Here we put the data in a manual way, find other method with arrays, loops or other things
        model.addElement(new Factura("Ceviche Pescado",cantidadFinal,"2500"));
        model.addElement(new Factura("Ceviche Pulpo",cantidadFinal,"3500"));
        model.addElement(new Factura("Ceviche Mixto",cantidadFinal,"6000"));
        model.addElement(new Factura("Ensalada Cesar",cantidadFinal,"1500"));
        model.addElement(new Factura("Ensalada Lechuga",cantidadFinal,"1500"));
        model.addElement(new Factura("Corte New York Steak",cantidadFinal,"18000"));
        model.addElement(new Factura("Corte Tomahawk",cantidadFinal,"20000"));
        model.addElement(new Factura("Corte Cow Boy",cantidadFinal,"20000"));
        model.addElement(new Factura("Corte Entraña",cantidadFinal,"20000"));
        model.addElement(new Factura("Cerveza",cantidadFinal,"1500"));
        model.addElement(new Factura("Tragos",cantidadFinal,"3000"));
        model.addElement(new Factura("Gaseosas",cantidadFinal,"1000"));
        model.addElement(new Factura("Naturales",cantidadFinal,"1500"));
        model.addElement(new Factura("Helado",cantidadFinal,"1500"));
        model.addElement(new Factura("Cheescake",cantidadFinal,"2500"));
    }
    
    // To put changes, go to window, in the table, in model, we put custom code and we add tableModel or the name of 
    // the reference we use for the object DefaultTableModel, to put all data into the table we have to go on table, go
    // to code and in Post-init-code we add the code we want
    private void addTableModel() {
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Precio");
        tableModel.addColumn("Cantidad");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        peopleItems = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        separator = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        mailLabel = new javax.swing.JLabel();
        mailText = new javax.swing.JTextField();
        titleOrder = new javax.swing.JLabel();
        spiner = new javax.swing.JSpinner();
        addButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logoGrande = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        principal = new javax.swing.JLabel();
        facturaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cerrarSesionLabel = new javax.swing.JLabel();
        addButton2 = new javax.swing.JButton();
        totalPagar = new javax.swing.JTextField();
        labelPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        peopleItems.setBackground(new java.awt.Color(255, 255, 255));
        peopleItems.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        peopleItems.setForeground(new java.awt.Color(102, 102, 102));
        peopleItems.setModel(model);
        peopleItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        addButton.setBackground(new java.awt.Color(36, 47, 65));
        addButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Añadir Pedido");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        productTable.setBackground(new java.awt.Color(255, 255, 255));
        productTable.setForeground(new java.awt.Color(51, 51, 51));
        productTable.setModel(tableModel);
        ListSelectionListener listener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) { // This does not duplicate the message
                    int selectedRow = productTable.getSelectedRow();
                    // The numbers as parameters represent the column of name,mail,phone etc, could change
                    String nombre = (String) tableModel.getValueAt(selectedRow, 0);
                    String precio = (String) tableModel.getValueAt(selectedRow, 1);
                    String cantidad = (String) tableModel.getValueAt(selectedRow, 2);

                    // Here we add the data into the textFields
                    nameText.setText(nombre);
                    lastNameText.setText(precio);
                    mailText.setText(cantidad);
                }
            }

        };

        productTable.getSelectionModel().addListSelectionListener(listener);
        scrollPanel.setViewportView(productTable);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(36, 47, 65));
        nameLabel.setText("Nombre");

        nameText.setBackground(new java.awt.Color(255, 255, 255));
        nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameText.setText(" ");
        nameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(36, 47, 65));
        lastNameLabel.setText("Precio");

        lastNameText.setBackground(new java.awt.Color(255, 255, 255));
        lastNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        mailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailLabel.setForeground(new java.awt.Color(36, 47, 65));
        mailLabel.setText("Cantidad");

        mailText.setBackground(new java.awt.Color(255, 255, 255));
        mailText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mailText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        titleOrder.setBackground(new java.awt.Color(36, 47, 65));
        titleOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titleOrder.setForeground(new java.awt.Color(36, 47, 65));
        titleOrder.setText("Ordenes de Compra");

        spiner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        addButton1.setBackground(new java.awt.Color(0, 102, 0));
        addButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addButton1.setForeground(new java.awt.Color(255, 255, 255));
        addButton1.setText("Pagar");
        addButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        logoGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoPequeño.png"))); // NOI18N

        menuLabel.setBackground(new java.awt.Color(36, 47, 65));
        menuLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Menu");
        menuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLabelMouseClicked(evt);
            }
        });

        principal.setBackground(new java.awt.Color(36, 47, 65));
        principal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        principal.setForeground(new java.awt.Color(255, 255, 255));
        principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        principal.setText("Principal");
        principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalMouseClicked(evt);
            }
        });

        facturaLabel.setBackground(new java.awt.Color(36, 47, 65));
        facturaLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        facturaLabel.setForeground(new java.awt.Color(255, 255, 255));
        facturaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facturaLabel.setText("Factura");
        facturaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facturaLabelMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (2).png"))); // NOI18N

        cerrarSesionLabel.setBackground(new java.awt.Color(36, 47, 65));
        cerrarSesionLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cerrarSesionLabel.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarSesionLabel.setText("Cerrar Sesión");
        cerrarSesionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoGrande)
                .addGap(61, 61, 61)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(facturaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrarSesionLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoGrande))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facturaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cerrarSesionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton2.setBackground(new java.awt.Color(255, 153, 0));
        addButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addButton2.setForeground(new java.awt.Color(255, 255, 255));
        addButton2.setText("Monto Pagar");
        addButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });

        totalPagar.setBackground(new java.awt.Color(255, 255, 255));
        totalPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelPago.setBackground(new java.awt.Color(255, 255, 255));
        labelPago.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelPago.setForeground(new java.awt.Color(36, 47, 65));
        labelPago.setText("Monto Total");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(mailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titleOrder)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(labelPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(peopleItems, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(spiner, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton1))))
                .addGap(43, 43, 43))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(peopleItems, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(spiner))
                        .addGap(36, 36, 36)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Obtener cantidad del spiner
        cantidad = 0;
        cantidad = (int) spiner.getValue();
        cantidadFinal = String.valueOf(cantidad);
        if (cantidad > 0) {
            Factura orden = (Factura) model.getSelectedItem();
            nombre = orden.getNombre();
            precio = orden.getPrecio();
            cantidades = cantidadFinal;
            //Creamos un string de toda la orden
            ordenCompra += "\n"+nombre+" "+cantidades+" "+precio;
            String[] pedido = {nombre, precio, cantidades};
            tableModel.addRow(pedido); // Here we add rows with the given data
        } else {
            JOptionPane.showMessageDialog(null, "Error, la cantidad no puede ser 0","Error Dato",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        Pago pago = new Pago(nom,ordenCompra, totalAbsoluto);
        pago.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addButton1ActionPerformed

    private void menuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLabelMouseClicked
        MenuProductos menu = new MenuProductos(nom);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLabelMouseClicked

    private void cerrarSesionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionLabelMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionLabelMouseClicked

    private void principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalMouseClicked
        PanelPrincipal principal = new PanelPrincipal(nom);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_principalMouseClicked

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        int columna1 = 0,columna2 = 0,totalProducto = 0;
        int totalFinal = 0;
        for (int i = 0; i < productTable.getRowCount(); i++) {
            if (!productTable.getValueAt(i, 2).toString().equals("0")) {
                columna1 = Integer.parseInt(productTable.getValueAt(i, 1).toString());
                columna2 = Integer.parseInt(productTable.getValueAt(i, 2).toString());
                totalProducto = columna1 * columna2;
                totalFinal += totalProducto;
            }
            else {
                columna1 = Integer.parseInt(productTable.getValueAt(i, 1).toString());
                columna2 = Integer.parseInt(productTable.getValueAt(i, 2).toString());
                totalProducto = columna1+columna2;
                totalFinal += totalProducto;
            }
        }
        totalAbsoluto = String.valueOf(totalFinal);
        totalPagar.setText(totalAbsoluto);
    }//GEN-LAST:event_addButton2ActionPerformed

    private void facturaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturaLabelMouseClicked
        // Enviamos los pedidos al metodo archivos persistentes
        if (!totalAbsoluto.equals("0") && !totalAbsoluto.equals(null)) {
            archivos.menuArchivos(nom, ordenCompra, totalAbsoluto);
        }
        else {
            JOptionPane.showMessageDialog(null, "Debe completar una compra o seleccionar monto a pagar","Revise Compra",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_facturaLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenar(nom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JLabel cerrarSesionLabel;
    private javax.swing.JLabel facturaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPago;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel logoGrande;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailText;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<Factura> peopleItems;
    private javax.swing.JLabel principal;
    private javax.swing.JTable productTable;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JSeparator separator;
    private javax.swing.JSpinner spiner;
    private javax.swing.JLabel titleOrder;
    private javax.swing.JTextField totalPagar;
    // End of variables declaration//GEN-END:variables
}
